package gui;

import cmd.CSV;
import cmd.Kusen;
import cmd.ConnectSQL;
import cmd.Kaca;
import cmd.Pekerja;
import java.sql.SQLException;
import java.util.concurrent.Semaphore;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author IRS37
 */
public class FrameAKS extends javax.swing.JFrame {

    /**
     * Creates new form FrameAKS
     */
    public FrameAKS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginMenu = new javax.swing.JDialog();
        userfield = new javax.swing.JFormattedTextField();
        passfield = new javax.swing.JPasswordField();
        userlabel = new javax.swing.JLabel();
        passlabel = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        dataKaca = new javax.swing.JDialog();
        okKaca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKaca = new javax.swing.JTable();
        tambahka = new javax.swing.JButton();
        hapuska = new javax.swing.JButton();
        dataKusen = new javax.swing.JDialog();
        okKusen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelKusen = new javax.swing.JTable();
        tambahku = new javax.swing.JButton();
        hapusku = new javax.swing.JButton();
        hasilKaca = new javax.swing.JDialog();
        banyakKaca = new javax.swing.JLabel();
        effKaca = new javax.swing.JLabel();
        banyakText = new javax.swing.JLabel();
        effText = new javax.swing.JLabel();
        hasilKusen = new javax.swing.JDialog();
        banyakKusen = new javax.swing.JLabel();
        effKusen = new javax.swing.JLabel();
        banyakText1 = new javax.swing.JLabel();
        effText1 = new javax.swing.JLabel();
        kacaDialog = new javax.swing.JDialog();
        panjangkaca = new javax.swing.JTextField();
        lebarkaca = new javax.swing.JTextField();
        kepadatankaca = new javax.swing.JTextField();
        OKka = new javax.swing.JButton();
        panjangkacaText = new javax.swing.JLabel();
        lebarkacaText = new javax.swing.JLabel();
        kepadatankacaText = new javax.swing.JLabel();
        saveKaca = new javax.swing.JButton();
        uploadKaca = new javax.swing.JButton();
        kusenDialog = new javax.swing.JDialog();
        panjangkusen = new javax.swing.JTextField();
        lebarkusen = new javax.swing.JTextField();
        bahankusen = new javax.swing.JTextField();
        OKKu = new javax.swing.JButton();
        panjangkusenText = new javax.swing.JLabel();
        lebarkusenText = new javax.swing.JLabel();
        bahankusenText = new javax.swing.JLabel();
        saveKusen = new javax.swing.JButton();
        uploadKusen = new javax.swing.JButton();
        berhasil = new javax.swing.JDialog();
        berhasilText = new javax.swing.JLabel();
        OKberhasil = new javax.swing.JButton();
        pekerjaDialog = new javax.swing.JDialog();
        waktuField = new javax.swing.JTextField();
        waktuText = new javax.swing.JLabel();
        OKWaktu = new javax.swing.JButton();
        hariText = new javax.swing.JLabel();
        waktuDialog = new javax.swing.JDialog();
        pekerjaField = new javax.swing.JTextField();
        pekerjaText = new javax.swing.JLabel();
        OKPekerja = new javax.swing.JButton();
        orangText = new javax.swing.JLabel();
        hasilPekerja = new javax.swing.JDialog();
        hasilPekerjaText = new javax.swing.JLabel();
        hasilWaktu = new javax.swing.JDialog();
        hasilWaktuText = new javax.swing.JLabel();
        gagalLogin = new javax.swing.JDialog();
        gagalText = new javax.swing.JLabel();
        notcon = new javax.swing.JDialog();
        notconText = new javax.swing.JLabel();
        menuKaca = new javax.swing.JButton();
        menuKusen = new javax.swing.JButton();
        pekerja = new javax.swing.JButton();
        waktu = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        close = new javax.swing.JMenuItem();
        user = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();

        userlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userlabel.setText("Username");

        passlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        passlabel.setText("Password");

        loginbutton.setText("LOGIN");
        loginbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginMenuLayout = new javax.swing.GroupLayout(loginMenu.getContentPane());
        loginMenu.getContentPane().setLayout(loginMenuLayout);
        loginMenuLayout.setHorizontalGroup(
            loginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(loginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginbutton)
                    .addGroup(loginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(passlabel)
                        .addComponent(userlabel)
                        .addComponent(userfield, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(passfield)))
                .addGap(24, 46, Short.MAX_VALUE))
        );
        loginMenuLayout.setVerticalGroup(
            loginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(userlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okKaca.setText("OK");
        okKaca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        okKaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okKacaActionPerformed(evt);
            }
        });

        tabelKaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Panjang", "Lebar", "Banyak"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelKaca.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelKaca);
        if (tabelKaca.getColumnModel().getColumnCount() > 0) {
            tabelKaca.getColumnModel().getColumn(0).setResizable(false);
            tabelKaca.getColumnModel().getColumn(1).setResizable(false);
            tabelKaca.getColumnModel().getColumn(2).setResizable(false);
            tabelKaca.getColumnModel().getColumn(3).setResizable(false);
        }

        tambahka.setText("Tambah baris");
        tambahka.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tambahka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkaActionPerformed(evt);
            }
        });

        hapuska.setText("Hapus baris");
        hapuska.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hapuska.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapuskaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataKacaLayout = new javax.swing.GroupLayout(dataKaca.getContentPane());
        dataKaca.getContentPane().setLayout(dataKacaLayout);
        dataKacaLayout.setHorizontalGroup(
            dataKacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKacaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapuska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(okKaca)
                .addContainerGap())
            .addGroup(dataKacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKacaLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        dataKacaLayout.setVerticalGroup(
            dataKacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKacaLayout.createSequentialGroup()
                .addContainerGap(393, Short.MAX_VALUE)
                .addGroup(dataKacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okKaca)
                    .addComponent(tambahka)
                    .addComponent(hapuska))
                .addContainerGap())
            .addGroup(dataKacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKacaLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        okKusen.setText("OK");
        okKusen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        okKusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okKusenActionPerformed(evt);
            }
        });

        tabelKusen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Panjang", "Lebar", "Banyak"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelKusen.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelKusen);
        if (tabelKusen.getColumnModel().getColumnCount() > 0) {
            tabelKusen.getColumnModel().getColumn(0).setResizable(false);
            tabelKusen.getColumnModel().getColumn(1).setResizable(false);
            tabelKusen.getColumnModel().getColumn(2).setResizable(false);
            tabelKusen.getColumnModel().getColumn(3).setResizable(false);
        }

        tambahku.setText("Tambah baris");
        tambahku.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tambahku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkuActionPerformed(evt);
            }
        });

        hapusku.setText("Hapus baris");
        hapusku.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hapusku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapuskuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataKusenLayout = new javax.swing.GroupLayout(dataKusen.getContentPane());
        dataKusen.getContentPane().setLayout(dataKusenLayout);
        dataKusenLayout.setHorizontalGroup(
            dataKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKusenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(okKusen)
                .addContainerGap())
            .addGroup(dataKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKusenLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        dataKusenLayout.setVerticalGroup(
            dataKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKusenLayout.createSequentialGroup()
                .addContainerGap(393, Short.MAX_VALUE)
                .addGroup(dataKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okKusen)
                    .addComponent(tambahku)
                    .addComponent(hapusku))
                .addContainerGap())
            .addGroup(dataKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKusenLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        banyakKaca.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        banyakKaca.setText("banyak");

        effKaca.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        effKaca.setText("eff");

        banyakText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        banyakText.setText("Banyak kaca :");

        effText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        effText.setText("Efisiensi :");

        javax.swing.GroupLayout hasilKacaLayout = new javax.swing.GroupLayout(hasilKaca.getContentPane());
        hasilKaca.getContentPane().setLayout(hasilKacaLayout);
        hasilKacaLayout.setHorizontalGroup(
            hasilKacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilKacaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(hasilKacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(banyakText)
                    .addComponent(effText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hasilKacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(effKaca)
                    .addComponent(banyakKaca))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        hasilKacaLayout.setVerticalGroup(
            hasilKacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilKacaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(hasilKacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banyakKaca)
                    .addComponent(banyakText))
                .addGap(38, 38, 38)
                .addGroup(hasilKacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(effKaca)
                    .addComponent(effText))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        banyakKusen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        banyakKusen.setText("banyak");

        effKusen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        effKusen.setText("eff");

        banyakText1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        banyakText1.setText("Banyak kusen :");

        effText1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        effText1.setText("Efisiensi :");

        javax.swing.GroupLayout hasilKusenLayout = new javax.swing.GroupLayout(hasilKusen.getContentPane());
        hasilKusen.getContentPane().setLayout(hasilKusenLayout);
        hasilKusenLayout.setHorizontalGroup(
            hasilKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilKusenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(hasilKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(effText1)
                    .addComponent(banyakText1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hasilKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(effKusen)
                    .addComponent(banyakKusen))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        hasilKusenLayout.setVerticalGroup(
            hasilKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilKusenLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(hasilKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banyakKusen)
                    .addComponent(banyakText1))
                .addGap(38, 38, 38)
                .addGroup(hasilKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(effKusen)
                    .addComponent(effText1))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        panjangkaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjangkacaActionPerformed(evt);
            }
        });

        lebarkaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lebarkacaActionPerformed(evt);
            }
        });

        kepadatankaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kepadatankacaActionPerformed(evt);
            }
        });

        OKka.setText("OK");
        OKka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKkaActionPerformed(evt);
            }
        });

        panjangkacaText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panjangkacaText.setText("Panjang");

        lebarkacaText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lebarkacaText.setText("Lebar");

        kepadatankacaText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kepadatankacaText.setText("Kepadatan");

        saveKaca.setText("Save");
        saveKaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveKacaActionPerformed(evt);
            }
        });

        uploadKaca.setText("Upload");
        uploadKaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadKacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kacaDialogLayout = new javax.swing.GroupLayout(kacaDialog.getContentPane());
        kacaDialog.getContentPane().setLayout(kacaDialogLayout);
        kacaDialogLayout.setHorizontalGroup(
            kacaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kacaDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(kacaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadKaca)
                    .addComponent(kepadatankacaText)
                    .addComponent(panjangkacaText)
                    .addComponent(lebarkacaText)
                    .addComponent(lebarkaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panjangkaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kacaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(kacaDialogLayout.createSequentialGroup()
                            .addComponent(saveKaca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OKka))
                        .addComponent(kepadatankaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        kacaDialogLayout.setVerticalGroup(
            kacaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kacaDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panjangkacaText)
                .addGap(13, 13, 13)
                .addComponent(panjangkaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lebarkacaText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lebarkaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kepadatankacaText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kepadatankaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(kacaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKka)
                    .addComponent(saveKaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uploadKaca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panjangkusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjangkusenActionPerformed(evt);
            }
        });

        lebarkusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lebarkusenActionPerformed(evt);
            }
        });

        bahankusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bahankusenActionPerformed(evt);
            }
        });

        OKKu.setText("OK");
        OKKu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKKuActionPerformed(evt);
            }
        });

        panjangkusenText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panjangkusenText.setText("Panjang");

        lebarkusenText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lebarkusenText.setText("Lebar");

        bahankusenText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bahankusenText.setText("Bahan");

        saveKusen.setText("Save");
        saveKusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveKusenActionPerformed(evt);
            }
        });

        uploadKusen.setText("Upload");
        uploadKusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadKusenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kusenDialogLayout = new javax.swing.GroupLayout(kusenDialog.getContentPane());
        kusenDialog.getContentPane().setLayout(kusenDialogLayout);
        kusenDialogLayout.setHorizontalGroup(
            kusenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kusenDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(kusenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadKusen)
                    .addComponent(bahankusen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bahankusenText)
                    .addComponent(panjangkusenText)
                    .addGroup(kusenDialogLayout.createSequentialGroup()
                        .addComponent(saveKusen)
                        .addGap(40, 40, 40)
                        .addComponent(OKKu))
                    .addComponent(lebarkusenText)
                    .addComponent(lebarkusen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panjangkusen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        kusenDialogLayout.setVerticalGroup(
            kusenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kusenDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panjangkusenText)
                .addGap(13, 13, 13)
                .addComponent(panjangkusen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lebarkusenText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lebarkusen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bahankusenText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bahankusen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(kusenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKKu)
                    .addComponent(saveKusen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uploadKusen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        berhasilText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        berhasilText.setText("Berhasil");

        OKberhasil.setText("OK");
        OKberhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKberhasilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout berhasilLayout = new javax.swing.GroupLayout(berhasil.getContentPane());
        berhasil.getContentPane().setLayout(berhasilLayout);
        berhasilLayout.setHorizontalGroup(
            berhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berhasilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(berhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, berhasilLayout.createSequentialGroup()
                        .addComponent(berhasilText)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, berhasilLayout.createSequentialGroup()
                        .addComponent(OKberhasil)
                        .addGap(99, 99, 99))))
        );
        berhasilLayout.setVerticalGroup(
            berhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, berhasilLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(berhasilText)
                .addGap(18, 18, 18)
                .addComponent(OKberhasil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        waktuField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuFieldActionPerformed(evt);
            }
        });

        waktuText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        waktuText.setText("Waktu Proyek :");

        OKWaktu.setText("OK");
        OKWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKWaktuActionPerformed(evt);
            }
        });

        hariText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hariText.setText("Hari");

        javax.swing.GroupLayout pekerjaDialogLayout = new javax.swing.GroupLayout(pekerjaDialog.getContentPane());
        pekerjaDialog.getContentPane().setLayout(pekerjaDialogLayout);
        pekerjaDialogLayout.setHorizontalGroup(
            pekerjaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pekerjaDialogLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(waktuText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waktuField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hariText)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pekerjaDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OKWaktu)
                .addGap(162, 162, 162))
        );
        pekerjaDialogLayout.setVerticalGroup(
            pekerjaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pekerjaDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pekerjaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waktuText)
                    .addComponent(waktuField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hariText))
                .addGap(18, 18, 18)
                .addComponent(OKWaktu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pekerjaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pekerjaFieldActionPerformed(evt);
            }
        });

        pekerjaText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pekerjaText.setText("Pekerja Proyek :");

        OKPekerja.setText("OK");
        OKPekerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKPekerjaActionPerformed(evt);
            }
        });

        orangText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        orangText.setText("Orang");

        javax.swing.GroupLayout waktuDialogLayout = new javax.swing.GroupLayout(waktuDialog.getContentPane());
        waktuDialog.getContentPane().setLayout(waktuDialogLayout);
        waktuDialogLayout.setHorizontalGroup(
            waktuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waktuDialogLayout.createSequentialGroup()
                .addGroup(waktuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(waktuDialogLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pekerjaText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pekerjaField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orangText))
                    .addGroup(waktuDialogLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(OKPekerja)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        waktuDialogLayout.setVerticalGroup(
            waktuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waktuDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(waktuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pekerjaText)
                    .addComponent(pekerjaField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orangText))
                .addGap(18, 18, 18)
                .addComponent(OKPekerja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hasilPekerjaText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hasilPekerjaText.setText("jLabel1");

        javax.swing.GroupLayout hasilPekerjaLayout = new javax.swing.GroupLayout(hasilPekerja.getContentPane());
        hasilPekerja.getContentPane().setLayout(hasilPekerjaLayout);
        hasilPekerjaLayout.setHorizontalGroup(
            hasilPekerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilPekerjaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(hasilPekerjaText)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        hasilPekerjaLayout.setVerticalGroup(
            hasilPekerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilPekerjaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hasilPekerjaText)
                .addContainerGap())
        );

        hasilWaktuText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hasilWaktuText.setText("jLabel1");

        javax.swing.GroupLayout hasilWaktuLayout = new javax.swing.GroupLayout(hasilWaktu.getContentPane());
        hasilWaktu.getContentPane().setLayout(hasilWaktuLayout);
        hasilWaktuLayout.setHorizontalGroup(
            hasilWaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilWaktuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(hasilWaktuText)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        hasilWaktuLayout.setVerticalGroup(
            hasilWaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilWaktuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hasilWaktuText)
                .addContainerGap())
        );

        gagalText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gagalText.setText("Salah Username/Password");

        javax.swing.GroupLayout gagalLoginLayout = new javax.swing.GroupLayout(gagalLogin.getContentPane());
        gagalLogin.getContentPane().setLayout(gagalLoginLayout);
        gagalLoginLayout.setHorizontalGroup(
            gagalLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gagalLoginLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(gagalText)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        gagalLoginLayout.setVerticalGroup(
            gagalLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gagalLoginLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(gagalText)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        notconText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        notconText.setText("Tidak terhubung ke basis data");

        javax.swing.GroupLayout notconLayout = new javax.swing.GroupLayout(notcon.getContentPane());
        notcon.getContentPane().setLayout(notconLayout);
        notconLayout.setHorizontalGroup(
            notconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notconLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(notconText)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        notconLayout.setVerticalGroup(
            notconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notconLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(notconText)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estimasi");

        menuKaca.setText("Menu Kaca");
        menuKaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKacaActionPerformed(evt);
            }
        });

        menuKusen.setText("Menu Kusen");
        menuKusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKusenActionPerformed(evt);
            }
        });

        pekerja.setText("Estimasi Pekerja");
        pekerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pekerjaActionPerformed(evt);
            }
        });

        waktu.setText("Estimasi Waktu");
        waktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuActionPerformed(evt);
            }
        });

        file.setText("File");

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        file.add(close);

        menuBar.add(file);

        user.setText("User");

        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        user.add(login);

        menuBar.add(user);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pekerja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuKaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuKusen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waktu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(menuKaca)
                .addGap(18, 18, 18)
                .addComponent(menuKusen)
                .addGap(18, 18, 18)
                .addComponent(pekerja)
                .addGap(18, 18, 18)
                .addComponent(waktu)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_closeActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        userfield.setText(null);
        passfield.setText(null);
        loginMenu.setLocationRelativeTo(null);
        loginMenu.setSize(280, 280);
        loginMenu.setLocation(460, 180);
        loginMenu.setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginMouseClicked

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
        username = userfield.getText();
        password = new String(passfield.getPassword());
        try {
            sql.connect(username, password, "mks");
            hasLogin = true;
            berhasil.setLocationRelativeTo(null);
            berhasil.setSize(250, 150);
            berhasil.setVisible(true);
            berhasil.setAlwaysOnTop(true);

        } catch (SQLException ex) {
        } catch (Exception ex) {
        }
        loginMenu.setVisible(false);
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void okKacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okKacaActionPerformed
        // TODO add your handling code here:
        KacaKusen.listKaca.clear();
        DefaultTableModel model = (DefaultTableModel) tabelKaca.getModel();
        int i, j, id, banyak = 0;
        float pa = 0, le;
        for (i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0) == null) {
                break;
            }
            id = (int) model.getValueAt(i, 0);
            pa = (float) model.getValueAt(i, 1);
            le = (float) model.getValueAt(i, 2);
            banyak = (int) model.getValueAt(i, 3);
            Kaca kaca = new Kaca(id, pa, le, KacaKusen.DataKaca.kepadatan);
            KacaKusen.listKaca.put(kaca, banyak);
        }
        banyakKaca.setText(Integer.toString(KacaKusen.banyakKaca()));
        effKaca.setText(Float.toString(KacaKusen.efektifKaca()));
        //banyakText.setText(Float.toString(KacaKusen.luasKaca));
        //effText.setText(Float.toString(KacaKusen.DataKaca.area));
        //banyakKaca.setText(Integer.toString(banyak));
        //effKaca.setText(Float.toString(pa));
        dataKaca.setVisible(false);
        kacaDialog.setVisible(true);
        kacaDialog.setAlwaysOnTop(true);
        hasilKaca.setLocationRelativeTo(null);
        hasilKaca.setSize(370, 220);
        hasilKaca.setVisible(true);
        hasilKaca.setAlwaysOnTop(true);
    }//GEN-LAST:event_okKacaActionPerformed

    private void tambahkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelKaca.getModel();
        model.addRow(new Object[]{null, null, null, null});
        //model.setValueAt(model.getRowCount(), 0, 0);
    }//GEN-LAST:event_tambahkaActionPerformed

    private void hapuskaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapuskaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelKaca.getModel();
        model.removeRow(model.getRowCount() - 1);
        //model.setValueAt(model.getRowCount(), 0, 0);
    }//GEN-LAST:event_hapuskaActionPerformed

    private void OKkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKkaActionPerformed
        // TODO add your handling code here:
        KacaKusen.infoKaca(Integer.parseInt(panjangkaca.getText()), Integer.parseInt(lebarkaca.getText()), Integer.parseInt(kepadatankaca.getText()));

        kacaDialog.setVisible(false);
        dataKaca.setLocationRelativeTo(null);
        dataKaca.setSize(500, 500);
        dataKaca.setVisible(true);
    }//GEN-LAST:event_OKkaActionPerformed

    private void kepadatankacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kepadatankacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kepadatankacaActionPerformed

    private void lebarkacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lebarkacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lebarkacaActionPerformed

    private void panjangkacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjangkacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panjangkacaActionPerformed

    private void panjangkusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjangkusenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panjangkusenActionPerformed

    private void lebarkusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lebarkusenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lebarkusenActionPerformed

    private void bahankusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bahankusenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bahankusenActionPerformed

    private void OKKuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKKuActionPerformed
        // TODO add your handling code here:
        KacaKusen.infoKusen(Integer.parseInt(panjangkusen.getText()), Integer.parseInt(lebarkusen.getText()), bahankusen.getText());

        kusenDialog.setVisible(false);
        dataKusen.setLocationRelativeTo(null);
        dataKusen.setSize(500, 500);
        dataKusen.setVisible(true);
    }//GEN-LAST:event_OKKuActionPerformed

    private void menuKacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKacaActionPerformed
        // TODO add your handling code here:
        kacaDialog.setLocationRelativeTo(null);
        kacaDialog.setSize(200, 400);
        kacaDialog.setVisible(true);
        kacaDialog.setAlwaysOnTop(true);
    }//GEN-LAST:event_menuKacaActionPerformed

    private void menuKusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKusenActionPerformed
        // TODO add your handling code here:
        kusenDialog.setLocationRelativeTo(null);
        kusenDialog.setSize(200, 400);
        kusenDialog.setVisible(true);
        kusenDialog.setAlwaysOnTop(true);
    }//GEN-LAST:event_menuKusenActionPerformed

    private void okKusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okKusenActionPerformed
        // TODO add your handling code here:
        KacaKusen.listKusen.clear();
        DefaultTableModel model = (DefaultTableModel) tabelKusen.getModel();
        int i, j, id, banyak = 0;
        float pa = 0, le;
        for (i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0) == null) {
                break;
            }
            id = (int) model.getValueAt(i, 0);
            pa = (float) model.getValueAt(i, 1);
            le = (float) model.getValueAt(i, 2);
            banyak = (int) model.getValueAt(i, 3);
            Kusen kusen = new Kusen(id, pa, le, KacaKusen.DataKusen.bahan);
            KacaKusen.listKusen.put(kusen, banyak);
        }
        banyakKusen.setText(Integer.toString(KacaKusen.banyakKusen()));
        effKusen.setText(Float.toString(KacaKusen.efektifKusen()));
        dataKusen.setVisible(false);
        hasilKusen.setLocationRelativeTo(null);
        hasilKusen.setSize(370, 220);
        hasilKusen.setVisible(true);
        hasilKusen.setAlwaysOnTop(true);
    }//GEN-LAST:event_okKusenActionPerformed

    private void tambahkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkuActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelKusen.getModel();
        model.addRow(new Object[]{null, null, null, null});
    }//GEN-LAST:event_tambahkuActionPerformed

    private void hapuskuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapuskuActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelKusen.getModel();
        model.removeRow(model.getRowCount() - 1);
    }//GEN-LAST:event_hapuskuActionPerformed

    private void uploadKacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadKacaActionPerformed
        try {
            sql.insertListKaca(KacaKusen.listKaca);
            berhasil.setLocationRelativeTo(null);
            berhasil.setSize(250, 150);
            berhasil.setVisible(true);
            berhasil.setAlwaysOnTop(true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_uploadKacaActionPerformed

    private void uploadKusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadKusenActionPerformed
        try {
            sql.insertListKusen(KacaKusen.listKusen);
            berhasil.setLocationRelativeTo(null);
            berhasil.setSize(250, 150);
            berhasil.setVisible(true);
            berhasil.setAlwaysOnTop(true);
        } catch (Exception ex) {
        }    }//GEN-LAST:event_uploadKusenActionPerformed

    private void saveKacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveKacaActionPerformed
        try {
            csv.writeKaca(KacaKusen.listKaca, "C:\\Users\\IRS37\\Google Drive\\PrototypeAKS\\kaca.csv");
            berhasil.setLocationRelativeTo(null);
            berhasil.setSize(250, 150);
            berhasil.setVisible(true);
            berhasil.setAlwaysOnTop(true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_saveKacaActionPerformed

    private void saveKusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveKusenActionPerformed
        try {
            csv.writeKusen(KacaKusen.listKusen, "C:\\Users\\IRS37\\Google Drive\\PrototypeAKS\\kusen.csv");
            berhasil.setLocationRelativeTo(null);
            berhasil.setSize(250, 150);
            berhasil.setVisible(true);
            berhasil.setAlwaysOnTop(true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_saveKusenActionPerformed

    private void waktuFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktuFieldActionPerformed

    private void pekerjaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pekerjaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pekerjaFieldActionPerformed

    private void OKWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKWaktuActionPerformed
        // TODO add your handling code here:
        int wkt = Pekerja.getWaktu(KacaKusen.banyakKaca + KacaKusen.banyakKusen, Integer.parseInt(waktuField.getText()));
        hasilWaktuText.setText(Integer.toString(wkt) + " orang");
        waktuDialog.setAlwaysOnTop(false);
        hasilWaktu.setLocationRelativeTo(null);
        hasilWaktu.setSize(250, 125);
        hasilWaktu.setVisible(true);
        hasilWaktu.setAlwaysOnTop(true);
    }//GEN-LAST:event_OKWaktuActionPerformed

    private void OKPekerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKPekerjaActionPerformed
        // TODO add your handling code here:
        int pkj = Pekerja.getPekerja(KacaKusen.banyakKaca + KacaKusen.banyakKusen, Integer.parseInt(pekerjaField.getText()));
        hasilPekerjaText.setText(Integer.toString(pkj) + " hari");
        pekerjaDialog.setAlwaysOnTop(false);
        hasilPekerja.setLocationRelativeTo(null);
        hasilPekerja.setSize(250, 125);
        hasilPekerja.setVisible(true);
        hasilPekerja.setAlwaysOnTop(true);
    }//GEN-LAST:event_OKPekerjaActionPerformed

    private void pekerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pekerjaActionPerformed
        // TODO add your handling code here:
        pekerjaDialog.setLocationRelativeTo(null);
        pekerjaDialog.setSize(400, 180);
        pekerjaDialog.setVisible(true);
        pekerjaDialog.setAlwaysOnTop(true);
    }//GEN-LAST:event_pekerjaActionPerformed

    private void waktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuActionPerformed
        // TODO add your handling code here:
        waktuDialog.setLocationRelativeTo(null);
        waktuDialog.setSize(400, 180);
        waktuDialog.setVisible(true);
        waktuDialog.setAlwaysOnTop(true);
    }//GEN-LAST:event_waktuActionPerformed

    private void OKberhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKberhasilActionPerformed
        // TODO add your handling code here:
        berhasil.setVisible(false);
    }//GEN-LAST:event_OKberhasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAKS().setVisible(true);
            }
        });
    }

    Semaphore count = new Semaphore(0);
    private String username;
    private String password;
    private ConnectSQL sql = new ConnectSQL();
    private CSV csv = new CSV();
    private boolean hasLogin = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKKu;
    private javax.swing.JButton OKPekerja;
    private javax.swing.JButton OKWaktu;
    private javax.swing.JButton OKberhasil;
    private javax.swing.JButton OKka;
    private javax.swing.JTextField bahankusen;
    private javax.swing.JLabel bahankusenText;
    private javax.swing.JLabel banyakKaca;
    private javax.swing.JLabel banyakKusen;
    private javax.swing.JLabel banyakText;
    private javax.swing.JLabel banyakText1;
    private javax.swing.JDialog berhasil;
    private javax.swing.JLabel berhasilText;
    private javax.swing.JMenuItem close;
    private javax.swing.JDialog dataKaca;
    private javax.swing.JDialog dataKusen;
    private javax.swing.JLabel effKaca;
    private javax.swing.JLabel effKusen;
    private javax.swing.JLabel effText;
    private javax.swing.JLabel effText1;
    private javax.swing.JMenu file;
    private javax.swing.JDialog gagalLogin;
    private javax.swing.JLabel gagalText;
    private javax.swing.JButton hapuska;
    private javax.swing.JButton hapusku;
    private javax.swing.JLabel hariText;
    private javax.swing.JDialog hasilKaca;
    private javax.swing.JDialog hasilKusen;
    private javax.swing.JDialog hasilPekerja;
    private javax.swing.JLabel hasilPekerjaText;
    private javax.swing.JDialog hasilWaktu;
    private javax.swing.JLabel hasilWaktuText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog kacaDialog;
    private javax.swing.JTextField kepadatankaca;
    private javax.swing.JLabel kepadatankacaText;
    private javax.swing.JDialog kusenDialog;
    private javax.swing.JTextField lebarkaca;
    private javax.swing.JLabel lebarkacaText;
    private javax.swing.JTextField lebarkusen;
    private javax.swing.JLabel lebarkusenText;
    private javax.swing.JMenuItem login;
    private javax.swing.JDialog loginMenu;
    private javax.swing.JButton loginbutton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton menuKaca;
    private javax.swing.JButton menuKusen;
    private javax.swing.JDialog notcon;
    private javax.swing.JLabel notconText;
    private javax.swing.JButton okKaca;
    private javax.swing.JButton okKusen;
    private javax.swing.JLabel orangText;
    private javax.swing.JTextField panjangkaca;
    private javax.swing.JLabel panjangkacaText;
    private javax.swing.JTextField panjangkusen;
    private javax.swing.JLabel panjangkusenText;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JLabel passlabel;
    private javax.swing.JButton pekerja;
    private javax.swing.JDialog pekerjaDialog;
    private javax.swing.JTextField pekerjaField;
    private javax.swing.JLabel pekerjaText;
    private javax.swing.JButton saveKaca;
    private javax.swing.JButton saveKusen;
    private javax.swing.JTable tabelKaca;
    private javax.swing.JTable tabelKusen;
    private javax.swing.JButton tambahka;
    private javax.swing.JButton tambahku;
    private javax.swing.JButton uploadKaca;
    private javax.swing.JButton uploadKusen;
    private javax.swing.JMenu user;
    private javax.swing.JFormattedTextField userfield;
    private javax.swing.JLabel userlabel;
    private javax.swing.JButton waktu;
    private javax.swing.JDialog waktuDialog;
    private javax.swing.JTextField waktuField;
    private javax.swing.JLabel waktuText;
    // End of variables declaration//GEN-END:variables
}
